import { EmptyNote, Panel, SubHeading } from "@/components/Panel";
import { formatDateTime } from "@/lib/format";
import type { AiHighlight, AiReview } from "@/lib/types";

/**
 * The AI editorial read.
 *
 * Deliberately unscored. Every other panel carries a number because a number is
 * defensible — it came from a check with evidence attached. This one is a model's
 * opinion, so it is presented as one: the claims are shown next to the evidence they
 * were drawn from, and the footer names the model and the time, because a reader has
 * to be able to discount it.
 */
function HighlightList({
  items,
  accent,
}: {
  items: AiHighlight[];
  accent: "good" | "warn";
}) {
  const mark = accent === "good" ? "var(--viz-good)" : "var(--viz-warn)";
  return (
    <ol className="space-y-2">
      {items.map((item) => (
        <li key={item.title} className="rounded-lg border border-line p-4">
          <p className="flex items-start gap-2 font-medium">
            <span
              aria-hidden
              className="mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full"
              style={{ backgroundColor: mark }}
            />
            {item.title}
          </p>
          <p className="mt-1.5 pl-4.5 text-sm text-ink-soft">{item.evidence}</p>
        </li>
      ))}
    </ol>
  );
}

export function AiReviewPanel({ review }: { review: AiReview | null }) {
  if (!review) {
    return (
      <Panel
        id="edge"
        title="Your edge"
        description="An AI read of what your work actually demonstrates."
      >
        <EmptyNote>
          No AI review on this report. Set GROQ_API_KEY in .env.local and re-analyze to
          get one.
        </EmptyNote>
      </Panel>
    );
  }

  return (
    <Panel
      id="edge"
      title="Your edge"
      description="What your work demonstrates, read by a model rather than measured by a checklist. Treat it as a second opinion, not a score."
    >
      <div className="space-y-6">
        {review.pitch && (
          <blockquote className="rounded-lg border border-brand/30 bg-brand-soft px-4 py-3">
            <p className="text-base font-medium text-ink">{review.pitch}</p>
            <footer className="mt-1 text-xs text-muted">
              The pitch this portfolio currently earns
            </footer>
          </blockquote>
        )}

        {review.positioning && (
          <div>
            <SubHeading>How this reads</SubHeading>
            <p className="text-sm leading-relaxed text-ink-soft">{review.positioning}</p>
          </div>
        )}

        {review.strengths.length > 0 && (
          <div>
            <SubHeading>Lead with this</SubHeading>
            <HighlightList items={review.strengths} accent="good" />
          </div>
        )}

        {review.underselling.length > 0 && (
          <div>
            <SubHeading>You are underselling</SubHeading>
            <HighlightList items={review.underselling} accent="warn" />
          </div>
        )}

        {(review.standoutProject || review.bestFitRoles.length > 0) && (
          <div className="grid gap-4 sm:grid-cols-2">
            {review.standoutProject && (
              <div className="rounded-lg bg-surface-2 p-4">
                <SubHeading>Strongest project</SubHeading>
                <p className="text-sm font-medium">{review.standoutProject}</p>
              </div>
            )}
            {review.bestFitRoles.length > 0 && (
              <div className="rounded-lg bg-surface-2 p-4">
                <SubHeading>Reads as competitive for</SubHeading>
                <ul className="flex flex-wrap gap-1.5">
                  {review.bestFitRoles.map((role) => (
                    <li
                      key={role}
                      className="rounded-md border border-line bg-surface px-2 py-0.5 text-sm"
                    >
                      {role}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}

        <p className="border-t border-line pt-3 text-xs text-muted">
          Generated by {review.model} on {formatDateTime(review.generatedAt)}. A model can
          be confidently wrong — check each claim against the evidence beside it. Your page
          content was sent to Groq to produce this.
        </p>
      </div>
    </Panel>
  );
}
